import manifest from './manifest.json';

/**
 * Which captures actually exist.
 *
 * PhoneFrame consults this instead of just trusting the filename a beat asks
 * for. Without it, a beat naming a capture that has not been shot yet renders an
 * <Img> pointing at a 404 — which comes out as a BLACK PHONE SCREEN, not as a
 * placeholder, and a black screen looks enough like a real dark-theme app screen
 * to reach an approval gate. Observed on 2026-08-21 on the confirm beat.
 *
 * The manifest is generated by `npm run collect`, so this is only as fresh as the
 * last collect run — which is the right coupling: collect is also what proves the
 * captures are distinct.
 */
const files: string[] = (manifest.screens ?? []).map((s: {file: string}) => s.file);

export const AVAILABLE = new Set<string>(files);

export const hasScreen = (name?: string): name is string =>
  Boolean(name && AVAILABLE.has(name));
